import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import React from "react";
import {Toaster} from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body className={inter.className}>
            <div className={'bg-auth-bg bg-cover bg-fixed'}>
                <main className="block">
                    <Toaster/>
                    <div className="flex w-full min-h-screen flex-col items-end justify-between z-10 top-0 left-0  ">

                        <div
                            className="relative flex flex-col xl:w-3/12 lg:w-4/12 md:w-full shadow-xl backdrop-blur  lg:gap-5 z-50 right-0 bg-[#ffffff99] justify-between font-mono text-sm lg:flex mb-15 min-h-screen h-full py-8">

                            {children}

                        </div>

                    </div>
                </main>
            </div>
        </body>
        </html>
);
}
