import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import React from "react";
import {Toaster} from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={'bg-auth-bg bg-cover bg-fixed'}>
            <main className="block">
                <Toaster/>
                <div className="flex w-full min-h-screen flex-col items-end justify-between z-10 top-0 left-0  ">
                    <div
                        className="flex flex-col xl:w-3/12 lg:w-4/12 md:w-8/12 md:mx-auto w-full mx-auto pb-10 shadow-xl rounded-xl lg:gap-5 z-50 m-auto bg-[#ffffff] justify-between font-mono text-sm lg:flex mb-15  py-8">

                        {children}

                    </div>

                </div>
            </main>
        </div>
    );
}
